#!/bin/sh
infiles=$@
trap 'rm -f $infiles; exit 1' 1 3 15

# echo ""
for infile in $infiles
do
  case $infile in
  *.h)
    cb="/*"; cs=" *"; ce=" */";;
  *.1|*.5|*.8|*.man)
    cb=.\\\"; cs=.\\\"; ce=.\\\";;
  *)
    case "`sed -n -e 1p $infile.in`" in
    '#!'*) cb="`sed -n -e 1p $infile.in`";;
    *)     cb="#";;
    esac
    cs="#"; ce="#";;
  esac
  echo "$cb"                                                    > $infile
  echo "$cs Generated automatically from $infile.in by the"     >> $infile
  echo "$cs configure script."                                  >> $infile
  echo "$ce"                                                    >> $infile
  echo "Creating $infile from $infile.in"
  sed -e '
s,@version@,man-1.6g,
s,@CC@,/Users/ariel/private-bin/clang,
s,@EXEEXT@,,
s,@BUILD_CC@,/Users/ariel/private-bin/clang,
s,@INSTALL@,install,
s,@DEFS@, -DSTDC_HEADERS -DTERMIOS_HEADER -DPOSIX -DDO_COMPRESS,
s,@LIBS@,,
s,@LIBOBJS@,,
s,@troff@,/usr/bin/groff -Tps -mandoc -c,
s,@nroff@,/usr/bin/groff -Wall -mtty-char -Tascii -mandoc -c,
s,@jnroff@,/usr/bin/groff -Tnippon -mandocj -c,
s,@eqn@,/usr/bin/eqn -Tps,
s,@neqn@,/usr/bin/eqn -Tascii,
s,@jneqn@,/usr/bin/eqn -Tnippon,
s,@tbl@,/usr/bin/tbl,
s,@nocol@,# ,
s,@pcol@,,
s,@col@,/usr/bin/col,
s,@vgrind@,,
s,@refer@,/usr/bin/refer,
s,@grap@,,
s,@pic@,/usr/bin/pic,
s,@fcat@,,
s,@pcat@,,
s,@zcat@,/usr/bin/zcat,
s,@unxz@,/usr/local/bin/unxz -c,
s,@gunzip@,/usr/bin/gunzip -c,
s,@bzip2@,/usr/bin/bzip2 -c -d,
s,@unlzma@,/usr/local/bin/unlzma -c -d,
s,@unyabba@,,
s,@compress@,/usr/local/bin/xz,
s,@compress_ext@,.xz,
s,@decompress@,/usr/local/bin/unxz -c,
s,@pager@,/usr/bin/less -is,
s,@browser@,/usr/bin/less -is,
s,@htmlpager@,/bin/cat,
s,@cmp@,/usr/bin/cmp -s,
s,@cat@,/bin/cat,
s,@awk@,/usr/bin/awk,
s,@bindir@,/usr/bin,
s,@sbindir@,/usr/sbin,
s,@mandir@,/usr/share/man,
s,@locale@,,
s,@fhs@,,
s,@fsstnd@,# ,
s,@man1ext@,1,g
s,@man5ext@,5,g
s,@man8ext@,8,g
s,@man_install_flags@,,
s,@man_user@,,
s,@languages@,en,
s,@man@,/usr/bin/man,
s,@apropos@,/usr/bin/apropos,
s,@whatis@,/usr/bin/whatis,
s,@man2dvi@,/usr/bin/man2dvi,
s,@makewhatis@,/usr/sbin/makewhatis,
s,@man_config_dir@,/private/etc,
s,@man_config_file@,/private/etc/man.conf,
s,@manpathoption@,--path,
s/@sections@/1:1p:8:2:3:3p:4:5:6:7:9:0p:tcl:n:l:p:o/
' $infile.in >> $infile
done
